services:
    - docker:dind

stages:
    - build
    - pack

go-build:
    image: golang:1.9
    stage: build
    script: 
        - mkdir -p $GOPATH/src/omi-gitlab.e-technik.uni-ulm.de/bwnetflow/kafka/
        - ln -s $PWD $GOPATH/src/omi-gitlab.e-technik.uni-ulm.de/bwnetflow/kafka/consumer_dashboard
        - go get -d -v ./...
        - go build -o consumer -v
    artifacts:
        paths:
            - consumer
      
docker-image:
    image: docker:latest
    stage: pack
    script:
        - TAG=$(date +%Y%m%d%H%M)
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
        - docker build --no-cache -t $CI_REGISTRY_IMAGE:$TAG .
        - if [ "$CI_COMMIT_REF_NAME" == "master" ]; then docker push $CI_REGISTRY_IMAGE:$TAG; fi
        - docker tag $CI_REGISTRY_IMAGE:$TAG $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
        - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

