# Build customization
builds:
  - main: .
    binary: consumer
    goos:
      - linux
    goarch:
      - amd64      

nfpm:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

  vendor: bwNetFlow
  homepage: https://bwNetflow.github.io/bwNetFlow/
  maintainer: bwNetFlow
  description: Kafka Consumer and Influx/Prometheus Exporter for a Grafana Dashboard
  license: GPL-3.0

  # Formats to be generated.
  formats:
    - deb
    - rpm

  # Override default /usr/local/bin destination for binaries
  bindir: /usr/bin

dockers:
  -
    goos: linux
    goarch: amd64
    goarm: ''
    image_templates:
    - 'bwnetflow/dashboard:{{ .Tag }}'
    - 'bwnetflow/dashboard:latest'
    extra_files:
    - docker-init
    - dist/linux_amd64