#!/bin/sh
echo "Start processor with kafka.brokers $KAFKA_BROKERS, kafka.topic $KAFKA_TOPIC, kafka.consumer_group $KAFKA_CONSUMER_GROUP"
/processor --kafka.brokers "$KAFKA_BROKERS" \
  --kafka.topic "$KAFKA_TOPIC" \
  --kafka.consumer_group "$KAFKA_CONSUMER_GROUP"