version: '2'
services:
  influxdb:
    image: influxdb:1.7-alpine
    restart: always
    stdin_open: true
    environment:
    - INFLUXDB_DB=bwnetflow
    - INFLUXDB_HTTP_AUTH_ENABLED=true
    - INFLUXDB_ADMIN_USER=admin
    - INFLUXDB_ADMIN_PASSWORD=secret
    ports:
     - 8086:8086

  chronograf:
    image: chronograf
    restart: always
    ports:
     - 8888:8888
    command: --influxdb-url=http://influxdb:8086

  grafana:
    image: grafana/grafana:latest
    ports:
    - 3000:3000/tcp
    environment:
      GF_DASHBOARDS_JSON_ENABLED: 'true'
      GF_SECURITY_ADMIN_PASSWORD: secret
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_SECRET_KEY: 1234